[package]
name = "battleship"
version = "0.1.0"
description = "Battleship game implemented in Rust"
authors = ["Orhun Parmaksız <orhunparmaksiz@gmail.com>"]
edition = "2021"

[dependencies]
fastrand = "1.7.0"
log = "0.4.14"
pretty_env_logger = "0.4.0"
